import { Speaker, Seminar } from "@/types/events";

export const speakers: Speaker[] = [
  {
    id: "speaker1",
    name: "Speaker 1",
    role: "Role1",
    company: "Company1",
    bio: "to add more details about the speaker",
    image: "/assets/speakers/Josh_Quinto.jpg",
    linkedin: "https://www.linkedin.com/in/joshquinto",
    topics: ["Risk Management", "Compliance", "FinTech"],
    schedule: "May 8, 2025 - 2:50 PM",
  },
  {
    id: "speaker2",
    name: "Speaker 2",
    role: "Role2",
    company: "Company2",
    bio: "to add more details about the speaker",
    image: "/assets/speakers/Josh_Quinto.jpg",
    linkedin: "https://www.linkedin.com/in/joshquinto",
    topics: ["Risk Management", "Compliance", "FinTech"],
    schedule: "May 8, 2025 - 2:50 PM",
  },
  {
    id: "speaker3",
    name: "Alpha Romer Coma",
    role: "GitHub Campus Expert",
    company: "GitHub Education",
    bio: "Alpha Romer Coma is a GitHub Campus Expert, a role that recognizes individuals who go above and beyond to support developer communities and foster growth among peers. He’s also an author at FreeCodeCamp, where he shares insights and tutorials with a global audience of learners, helping make complex technical topics more accessible to everyone. Professionally, his certifications speak volumes—5x GitHub Certified across areas like administration, advanced security, actions, foundations, and Copilot; 4x Microsoft Certified, including as an AI Engineer; and 2x Google Cloud Certified with credentials as an Associate Cloud Engineer and a Cloud Digital Leader. Beyond the certifications, he is deeply committed to giving back. He volunteers actively with Google Developer Groups Cloud Manila, helping drive conversations around cloud technologies and empowering local developers through events and mentorship.",
    image: "/assets/speakers/Josh_Quinto.jpg",
    linkedin: "https://www.linkedin.com/in/joshquinto",
    topics: ["Risk Management", "Compliance", "FinTech"],
    schedule: "May 8, 2025 - 2:50 PM",
  },
  {
    id: "speaker4",
    name: "Daniel Caparro",
    role: "Chief Executive Officer",
    company: "ElectrifAI PH Solutions Corp.",
    bio: "Daniel Caparro is the CEO of ElectrifAI PH Solutions Corp., a dynamic leader and innovative AI engineer whose expertise bridges advanced artificial intelligence techniques with impactful real-world applications. A graduate of the Polytechnic University of the Philippines with a degree in Electronics Engineering, he has made significant strides in natural language processing, deep learning, and data-driven software solutions, delivering generative AI-powered systems that optimize workflows, enhance recruitment, and fight misinformation. Beyond his professional work, Daniel has held leadership roles in tech organizations, contributed to global research competitions, and continues to shape the future of technology through mentorship, collaboration, and a passion for AI for social good.",
    image: "/assets/speakers/Daniel_Caparro.jpg",
    linkedin: "https://www.linkedin.com/in/daniel-caparro-805682224/",
    topics: ["Artificial Intelligence", "Natural Language Processing", "Machine Learning", "Deep Learning", "Computer Vision", "Data Engineering", "MLOps"],
    schedule: "May 8, 2025 - 2:50 PM",
  },
  {
    id: "speaker5",
    name: "Engr. Raniel Christian Agno",
    role: "Senior CRM Developer",
    company: "QIAGEN Business Services Manila",
    bio: "Engr. Raniel Christian Agno is a Salesforce Developer with extensive experience in the information technology and services industry. A graduate of the Polytechnic University of the Philippines with a degree in Computer Engineering, he began his professional journey as an Associate Salesforce Consultant at Simplus from 2018 to 2020. Since then, he has been serving as a Senior CRM Developer at QIAGEN Business Services Manila, where he continues to develop and optimize Salesforce-based solutions. Skilled in Apex Data Loader, AngularJS, and certified as a Salesforce.com Developer, Raniel holds multiple recent certifications including Salesforce Certified AI Specialist, AI Associate, and Identity and Access Management Architect. His expertise reflects a strong commitment to innovation in CRM and AI-driven technologies.",
    image: "/assets/speakers/Raniel_Agno.jpg",
    linkedin: "https://www.linkedin.com/in/ranielagno/",
    topics: ["Customer Relationship Management (CRM)", "Salesforce Development", "Apex Data Loader", "AngularJS"],
    schedule: "May 8, 2025 - 2:50 PM",
  },
  {
    id: "speaker6",
    name: "Engr. Janine Tan",
    role: "SAP MDG (Consultant)",
    company: "Goodyear Business Services",
    bio: "Engr. Janine Tan is an experienced SAP Master Data Governance (MDG) Consultant and a graduate of the Polytechnic University of the Philippines with a degree in Computer Engineering, Batch 2018. She began her career at Accenture as an SAP MDG Consultant, later joining Fujitsu as an SAP Functional Consultant, and currently serves as a Global SAP Process Consultant at The Goodyear Tire and Rubber Company. With a strong foundation in data governance and enterprise systems, Janine holds certifications including the SAP Certified Application Associate for S/4HANA MDG and Google’s cybersecurity fundamentals. Her expertise spans SAP MDG implementation, data management, and risk-aware process optimization in global business environments.",
    image: "/assets/speakers/Janine_Tan.jpg",
    linkedin: "https://www.linkedin.com/in/janine-tan-01097a167/",
    topics: ["Master Data Governance (MDG)", "Enterprise Resource Planning (ERP)", "SAP S/4HANA", "Data Management"],
    schedule: "May 8, 2025 - 2:50 PM",
  },
  {
    id: "speaker7",
    name: "Dr. Rufo Marasigan",
    role: "Professor",
    company: "PUP OUS and Graduate School",
    bio: "Dr. Rufo I. Marasigan Jr. holds a Doctor of Engineering in Computer Engineering, specializing in the application of Artificial Intelligence in agriculture. His research integrates experimental and computational approaches in applied machine learning, with a particular focus on forestry assessment. Dr. Marasigan is actively involved in several DOST- and CHED-funded projects, including the Digitization of Dance Kinematics of Indigenous People and the Mangrove Project. He has been recognized as a visiting scholar under the CHED PCARI-DEVICE Program at the UC Berkeley College of Engineering, where he worked on machine learning applications. Additionally, he is a recipient of the CHED FD-II scholarship grant for graduate studies. His expertise spans unmanned aerial vehicles (UAVs), machine learning in agricultural precision farming, embedded system development, web development, and blockchain technology. Beyond his research, Engr. Marasigan contributes as a software developer and oversees various research initiatives within his department.",
    image: "/assets/speakers/Rufo_Marasigan.png",
    linkedin: "https://www.linkedin.com/in/rmarasiganjr/",
    topics: ["Artificial Intelligence", "Agriculture", "Machine Learning", "Forestry Assessment", "UAVs", "Embedded System Development", "Blockchain"],
    schedule: "May 8, 2025 - 2:50 PM",
  },
  {
    id: "speaker8",
    name: "Mr. Adrian Cayaco",
    role: "Head of AI Engineering",
    company: "Stratpoint Technologies",
    bio: "Mr. Adrian Cayaco is the Head of AI Engineering at Stratpoint Technologies, Inc., with over 12 years of experience in software engineering and technical leadership. He began his career at Stratpoint in 2014 and has steadily advanced through roles. In his leadership role, he oversees the development and implementation of AI-driven solutions, guiding a team of engineers to drive innovation and technical excellence. Mr. Cayaco holds a Bachelor of Science in Computer Engineering and a Master of Science in Electrical Engineering from the University of the Philippines. His extensive experience in the software engineering industry, combined with his technical expertise in AI, allows him to lead cutting-edge projects at Stratpoint Technologies, shaping the future of AI solutions in various industries.",
    image: "/assets/speakers/Adrian_Cayaco.jpg",
    linkedin: "https://www.linkedin.com/in/adrian-cayaco-60141390/",
    topics: ["Artificial Intelligence Engineering", "Technical Project Management", "Software Engineering"],
    schedule: "May 8, 2025 - 2:50 PM",
  },
  {
    id: "speaker9",
    name: "Romeo Nicklaus Advincula",
    role: "Lead Curriculum Developer and Senior Instructor",
    company: "STEAMlab",
    bio: "Romeo Nicklaus Advincula is the Lead Curriculum Developer and Senior Instructor at STEAMlab, where he helps shape dynamic, hands-on learning experiences in STEM and robotics. He is a senior lead for Arduino Day Philippines and a dedicated volunteer with both IoT Conference Philippines and DevCon, where he actively supports initiatives like Hour of Code—helping young minds take their first steps into the world of programming and embedded systems. A passionate educator, he regularly speaks at universities across the country, championing the importance of robotics and embedded systems in today’s world. His technical excellence has been recognized in several machine design competitions, and he was awarded 2nd place in the prestigious Gawad TIP Awards, honoring outstanding contributions from the Technological Institute of the Philippines community.",
    image: "/assets/speakers/josh_quinto.jpg",
    linkedin: "https://www.linkedin.com/in/joshquinto",
    topics: ["Risk Management", "Compliance", "FinTech"],
    schedule: "May 8, 2025 - 2:50 PM",
  },
  {
    id: "speaker10",
    name: "Josh Quinto, DBA, CRA",
    role: "Chief Risk and Compliance Officer",
    company: "PayMongo",
    bio: "Josh Quinto is a degree holder of Doctor of Business Administration with 19 years of intensive experience in financial institutions and FinTechs. He currently serves as the Chief Risk and Compliance Officer at PayMongo and sits on the Board of Trustees of the Association of Remittance Compliance Officers. He is a Certified Risk Analyst (CRA®) accredited by the Global Academy of Finance and Management, and is also certified in Bank Risk Management by the Asian Institute of Chartered Bankers. Additionally, he holds a Six Sigma Green Belt certification from Six Sigma Philippines. He has held key roles in organizations such as Maya, Uploan PH, PNB, EastWest Bank, UniCapital Inc., and BPI, bringing a wealth of expertise in risk, compliance, and financial strategy.",
    image: "/assets/speakers/Josh_Quinto.jpg",
    linkedin: "https://www.linkedin.com/in/josh-quinto-dba-cra-4b473a46/",
    topics: ["Risk Management", "Compliance", "FinTech"],
    schedule: "May 8, 2025 - 2:50 PM",
  }
]  

export const seminars: Seminar[] = [
  {
    id: "seminar1",
    title: "Cracking the Code Behind Big Data",
    description: "Discover what Big Data is and how it is transforming industries like healthcare and finance. Get introduced to powerful tools like Hadoop, Spark, and cloud platforms through demos and real-world examples",
    date: "May 5, 2025",
    time: "2:50 PM",
    duration: 50,
    topics: ["Big Data", "Hadoop", "Spark", "Cloud Computing"],
    speakerId: "speaker1",
  },
  {
    id: "seminar2",
    title: "From Raw Data to Career-Ready Skills",
    description: "Learn the basics of data collection, cleaning, and visualization using beginner-friendly tools like Tableau and Power BI. Explore career paths in Big Data and how to build a strong data portfolio.",
    date: "May 6, 2025",
    time: "9:35 AM",
    duration: 50,
    topics: ["Big Data", "Data Collection", "Data Cleaning", "Data Visualization", "Tableau", "Power BI"],
    speakerId: "speaker2",
  },
  {
    id: "seminar3",
    title: "Streamlining Project Management with GitHub: Collaboration, Version Control, and Workflow Optimization",
    description: "Master Git and GitHub for version control, collaboration, and project workflow. Learn key practices like branching, pull requests, and conflict resolution.",
    date: "May 6, 2025",
    time: "10:50 AM",
    duration: 50,
    topics: ["GitHub", "Git", "Version Control"],
    speakerId: "speaker3",
  },
  {
    id: "seminar4",
    title: "AiLearn to AiEarn: Master Skills, Create Profits",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    date: "May 6, 2025",
    time: "1:05 PM",
    duration: 50,
    topics: ["Lorem", "ipsum", "dolor"],
    speakerId: "speaker4",
  },
  {
    id: "seminar5",
    title: "The Power of Connection: Exploring the Salesforce World",
    description: "Offers students an engaging introduction to Salesforce, the world's leading cloud-based platform for managing customer relationships. We'll delve into how Salesforce empowers businesses to connect with their customers in meaningful ways, streamline sales and marketing efforts, and gain valuable insights. Discover the vast ecosystem of Salesforce tools and learn how understanding this platform can open doors to exciting career opportunities in today's interconnected business landscape.",
    date: "May 6, 2025",
    time: "2:20 PM",
    duration: 50,
    topics: ["Lorem", "ipsum", "dolor"],
    speakerId: "speaker5",
  },
  {
    id: "seminar6",
    title: "The SAP Advantage: Streamlining Your Business Operations",
    description: "Offers students a clear and accessible introduction to SAP, a leading enterprise software used by organizations worldwide. We'll demystify the complexities of SAP, revealing how its integrated systems manage crucial business functions and drive efficiency across industries. Discover the fundamental concepts behind enterprise resource planning (ERP) and gain insights into how SAP powers global operations, making it a vital skill for future business professionals.",
    date: "May 6, 2025",
    time: "3:35 PM",
    duration: 50,
    topics: ["Lorem", "ipsum", "dolor"],
    speakerId: "speaker6",
  },
  {
    id: "seminar7",
    title: "Demystifying Artificial Intelligence: Guide to Understanding and Navigating the Age of AI",
    description: "It will provide clear and accessible introduction to the world of Artificial Intelligence. We cut through the hype and misconceptions, offering a foundational understanding of core AI concepts, real-world applications, and the current state of the technology. To gain a practical perspective on what AI truly is and what it can (and cannot) do, empowering you to navigate the AI landscape with clarity and informed insights.",
    date: "May 8, 2025",
    time: "9:35 AM",
    duration: 50,
    topics: ["Lorem", "ipsum", "dolor"],
    speakerId: "speaker7",
  },
  {
    id: "seminar8",
    title: "From Pixels to Insights: Machine Learning for Image Processing and Analysis",
    description: "It will delve into the exciting world of using machine learning to extract valuable information from images. You'll learn how algorithms can be trained to understand visual data, enabling applications like image recognition, object detection, and more. This session will bridge the gap between raw image data and actionable insights, providing a foundational understanding of this rapidly evolving field.",
    date: "May 8, 2025",
    time: "10:50 AM",
    duration: 50,
    topics: ["Lorem", "ipsum", "dolor"],
    speakerId: "speaker8",
  },
  {
    id: "seminar9",
    title: "Rise of the Machines: Exploring the World of Robotics",
    description: "Discover the building blocks of intelligent machines, from sensors to AI integration. Explore how robotics is transforming industries and dive into the future of robotics, including key challenges and emerging opportunities.",
    date: "May 8, 2025",
    time: "1:35 PM",
    duration: 50,
    topics: ["Robotics", "Artificial Intelligence", "Sensors"],
    speakerId: "speaker9",
  },
  {
    id: "seminar10",
    title: "A Day in Fintech: Transforming Finance Through Innovation",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    date: "May 8, 2025",
    time: "2:50 PM",
    duration: 50,
    topics: ["Lorem", "ipsum", "dolor"],
    speakerId: "speaker10",
  }
]

export const getSeminarsBySpeaker = (speakerId: string): Seminar[] => {
  return seminars.filter(seminar => seminar.speakerId === speakerId);
};

export const getSpeakerBySeminar = (seminarId: string): Speaker | undefined => {
  const seminar = seminars.find(s => s.id === seminarId);
  if (!seminar) return undefined;
  return speakers.find(speaker => speaker.id === seminar.speakerId);
};
