import { Speaker, Seminar } from "@/types/events";

export const speakers: Speaker[] = [
  {
    id: "speaker1",
    name: "John Paul Ada",
    role: "Data Engineer",
    company: "NextPay",
    bio: "John Paul Ada is currently working as a Data Engineer at NextPay. He previously held roles at Globe Telecom and IBM, where he contributed to large-scale data engineering initiatives. His career began with a passion for teaching, starting out as a tutor—something that continues to inform his approach to mentorship and knowledge sharing. With deep expertise in Data Engineering and AI, Josh works at the forefront of innovation, leveraging cloud-based solutions to build scalable. He holds multiple certifications, including Google Certified Educator and Microsoft Certified: Azure Data Engineer Associate. Beyond his engineering work, he's also an active voice in the local tech scene, having spoken at events like the TensorFlow Dev Summit and Facebook Developer Circle, helping push the boundaries of what’s possible with the Philippine tech scene.",
    image: "/assets/speakers/John_Paul_Ada.jpg",
    linkedin: "https://www.linkedin.com/in/john-paul-ada/",
    topics: ["Data Engineering", "Cloud Computing", "AI Innovation", "Tech Education", "Big Data"],
  },
  {
    id: "speaker2",
    name: "Rhon Joshua Calupitan",
    role: "Data Pipeline Engineer",
    company: "Globe Telecom",
    bio: "Rhon Joshua Calupitan is a dynamic professional at the intersection of technology, data, and creativity. Josh is a Computer Engineer and seasoned IT expert, known for driving innovation through Data Engineering, AI, and Automation. His work spans across Natural Language Processing, Large Language Models, and Robotic Process Automation, with a strong foundation in both Amazon Web Services and Google Cloud Platform for delivering robust, cloud-based solutions. Professionally, he has held impactful roles, including Expert in Data Pipeline Engineering at Globe Telecom, and previously as a Data Engineering, Management, and Governance Analyst at Accenture Philippines, where he helped shape large-scale data systems and strategies.",
    image: "/assets/speakers/Rhon_Joshua_Calupitan.jpg",
    linkedin: "https://www.linkedin.com/in/rjvcalupitan/",
    topics: ["Data Engineering", "AI & Automation", "Cloud Computing", "NLP", "LLMs", "RPA"],
  },
  {
    id: "speaker3",
    name: "Alpha Romer Coma",
    role: "GitHub Campus Expert",
    company: "GitHub Education",
    bio: "Alpha Romer Coma is a GitHub Campus Expert, a role that recognizes individuals who go above and beyond to support developer communities and foster growth among peers. He’s also an author at FreeCodeCamp, where he shares insights and tutorials with a global audience of learners, helping make complex technical topics more accessible to everyone. Professionally, his certifications speak volumes—5x GitHub Certified across areas like administration, advanced security, actions, foundations, and Copilot; 4x Microsoft Certified, including as an AI Engineer; and 2x Google Cloud Certified with credentials as an Associate Cloud Engineer and a Cloud Digital Leader. Beyond the certifications, he is deeply committed to giving back. He volunteers actively with Google Developer Groups Cloud Manila, helping drive conversations around cloud technologies and empowering local developers through events and mentorship.",
    image: "/assets/speakers/Alpha_Romer_Coma.png",
    linkedin: "https://www.linkedin.com/in/alpharomercoma/",
    topics: ["GitHub", "Cloud Computing", "AI Engineering", "Technical Writing"]
  },
  {
    id: "speaker8",
    name: "Daniel Caparro",
    role: "Chief Executive Officer",
    company: "ElectrifAI PH Solutions Corp.",
    bio: "Daniel Caparro is the CEO of ElectrifAI PH Solutions Corp., a dynamic leader and innovative AI engineer whose expertise bridges advanced artificial intelligence techniques with impactful real-world applications. A graduate of the Polytechnic University of the Philippines with a degree in Electronics Engineering, he has made significant strides in natural language processing, deep learning, and data-driven software solutions, delivering generative AI-powered systems that optimize workflows, enhance recruitment, and fight misinformation. Beyond his professional work, Daniel has held leadership roles in tech organizations, contributed to global research competitions, and continues to shape the future of technology through mentorship, collaboration, and a passion for AI for social good.",
    image: "/assets/speakers/Daniel_Caparro.png",
    linkedin: "https://www.linkedin.com/in/daniel-caparro-805682224/",
    topics: ["Artificial Intelligence", "Natural Language Processing", "Machine Learning", "Deep Learning", "Computer Vision", "Data Engineering", "MLOps"],
  },
  {
    id: "speaker5",
    name: "Engr. Raniel Christian Agno",
    role: "Senior CRM Developer",
    company: "QIAGEN Business Services Manila",
    bio: "Engr. Raniel Christian Agno is a Salesforce Developer with extensive experience in the information technology and services industry. A graduate of the Polytechnic University of the Philippines with a degree in Computer Engineering, he began his professional journey as an Associate Salesforce Consultant at Simplus from 2018 to 2020. Since then, he has been serving as a Senior CRM Developer at QIAGEN Business Services Manila, where he continues to develop and optimize Salesforce-based solutions. Skilled in Apex Data Loader, AngularJS, and certified as a Salesforce.com Developer, Raniel holds multiple recent certifications including Salesforce Certified AI Specialist, AI Associate, and Identity and Access Management Architect. His expertise reflects a strong commitment to innovation in CRM and AI-driven technologies.",
    image: "/assets/speakers/Raniel_Agno.png",
    linkedin: "https://www.linkedin.com/in/ranielagno/",
    topics: ["Customer Relationship Management (CRM)", "Salesforce Development", "Apex Data Loader", "AngularJS"],
  },
  {
    id: "speaker6",
    name: "Engr. Janine Tan",
    role: "SAP MDG (Consultant)",
    company: "Goodyear Business Services",
    bio: "Engr. Janine Tan is an experienced SAP Master Data Governance (MDG) Consultant and a graduate of the Polytechnic University of the Philippines with a degree in Computer Engineering, Batch 2018. She began her career at Accenture as an SAP MDG Consultant, later joining Fujitsu as an SAP Functional Consultant, and currently serves as a Global SAP Process Consultant at The Goodyear Tire and Rubber Company. With a strong foundation in data governance and enterprise systems, Janine holds certifications including the SAP Certified Application Associate for S/4HANA MDG and Google’s cybersecurity fundamentals. Her expertise spans SAP MDG implementation, data management, and risk-aware process optimization in global business environments.",
    image: "/assets/speakers/Janine_Tan.png",
    linkedin: "https://www.linkedin.com/in/janine-tan-01097a167/",
    topics: ["Master Data Governance (MDG)", "Enterprise Resource Planning (ERP)", "SAP S/4HANA", "Data Management"],
  },
  {
    id: "speaker7",
    name: "Dr. Rufo Marasigan",
    role: "Professor",
    company: "PUP OUS and Graduate School",
    bio: "Dr. Rufo I. Marasigan Jr. holds a Doctor of Engineering in Computer Engineering, specializing in the application of Artificial Intelligence in agriculture. His research integrates experimental and computational approaches in applied machine learning, with a particular focus on forestry assessment. Dr. Marasigan is actively involved in several DOST- and CHED-funded projects, including the Digitization of Dance Kinematics of Indigenous People and the Mangrove Project. He has been recognized as a visiting scholar under the CHED PCARI-DEVICE Program at the UC Berkeley College of Engineering, where he worked on machine learning applications. Additionally, he is a recipient of the CHED FD-II scholarship grant for graduate studies. His expertise spans unmanned aerial vehicles (UAVs), machine learning in agricultural precision farming, embedded system development, web development, and blockchain technology. Beyond his research, Engr. Marasigan contributes as a software developer and oversees various research initiatives within his department.",
    image: "/assets/speakers/Rufo_Marasigan.png",
    linkedin: "https://www.linkedin.com/in/rmarasiganjr/",
    topics: ["Artificial Intelligence", "Agriculture", "Machine Learning", "Forestry Assessment", "UAVs", "Embedded System Development", "Blockchain"],
  },
  {
    id: "speaker4",
    name: "Dr. Cherry D. Casuat, DEng-CpE, PCpE",
    role: "Professor",
    company: "PUP OUS and Graduate School",
    bio: "Dr. Cherry D. Casuat, DEng-CpE, PCpE, is a Professional Computer Engineer and esteemed faculty member at the Polytechnic University of the Philippines (PUP) Manila, serving in the College of Engineering, Graduate School, and Open University System. She holds a Doctor of Engineering degree with a specialization in Computer Engineering and has an extensive academic and professional background, including a Master of Engineering and a Bachelor of Science in Computer Engineering. Dr. Casuat has authored numerous research papers published in Scopus-indexed journals, focusing on artificial intelligence, IoT, smart systems, and digital learning innovations. She has received several international recognitions, including the 1st Best Research Paper Award in the International Conference on Humanities, Engineering, Sciences, Management, Education and Technology 2025 in Malaysia; 2nd Best Research Paper Award in the International Conference on Humanities, Engineering, Sciences, Management, Education and Technology 2023 in Bangkok, Thailand; and Second Place in the Industrial Engineering Operations and Management Supply Chain and Logistics Competition in Augsburg, Germany. An active international reviewer for IEEE conferences, she also serves as the LMS Coordinator for PUP campuses and is the Treasurer of the Mechatronics and Robotics Society of the Philippines (MRSP) – NCR Chapter. Dr. Casuat is a lifetime member of ICpEP and MRSP and an active member of IEEE, DOST-National Research Council of the Philippines, and other professional organizations, continuously contributing to research, education, and technological advancement.",
    image: "/assets/speakers/Cherry_Casuat.jpg",
    linkedin: "https://www.linkedin.com/in/cherry-casuat-5440ab143/",
    topics: ["Artificial Intelligence", "Internet of Things (IoT)", "Smart Systems", "Digital Learning Innovations"],
  },
  {
    id: "speaker9",
    name: "Romeo Nicklaus Advincula",
    role: "Lead Curriculum Developer and Senior Instructor",
    company: "STEAMlab",
    bio: "Romeo Nicklaus Advincula is the Lead Curriculum Developer and Senior Instructor at STEAMlab, where he helps shape dynamic, hands-on learning experiences in STEM and robotics. He is a senior lead for Arduino Day Philippines and a dedicated volunteer with both IoT Conference Philippines and DevCon, where he actively supports initiatives like Hour of Code—helping young minds take their first steps into the world of programming and embedded systems. A passionate educator, he regularly speaks at universities across the country, championing the importance of robotics and embedded systems in today’s world. His technical excellence has been recognized in several machine design competitions, and he was awarded 2nd place in the prestigious Gawad TIP Awards, honoring outstanding contributions from the Technological Institute of the Philippines community.",
    image: "/assets/speakers/Romeo_Nicklaus_Advincula.png",
    linkedin: "https://www.linkedin.com/in/romeonicklausadvincula/",
    topics: ["Robotics", "Embedded Systems", "IoT", "Curriculum Development"],
  },
  {
    id: "speaker10",
    name: "Josh Quinto, DBA, CRA",
    role: "Chief Risk and Compliance Officer",
    company: "PayMongo",
    bio: "Josh Quinto is a seasoned executive with over 20 years of experience in the banking and fintech industries, with deep expertise in enterprise risk, operational risk, credit risk, and risk consulting. He currently serves as the Chief Risk & Compliance Officer at PayMongo, where he leads the design and execution of the company’s enterprise risk management and compliance strategies. Before joining PayMongo, Josh held senior risk management roles in several prominent institutions, including Maya, Savii, Philippine National Bank (PNB), EastWest Bank, Unicapital, and Bank of the Philippine Islands (BPI). His broad industry experience has given him a comprehensive and practical understanding of risk management across a variety of business models and regulatory environments. Josh holds a Doctor in Business Administration (DBA) and a Master in Business Administration (MBA), both from the Polytechnic University of the Philippines (PUP) Manila. He is a Certified Risk Analyst (CRA) accredited by the Global Academy of Finance and Management and currently serves as a member of the Board of Trustees of the Association of Remittance Company Compliance Officers (ARCCO).",
    image: "/assets/speakers/Josh_Quinto.jpg",
    linkedin: "https://www.linkedin.com/in/josh-quinto-dba-cra-4b473a46/",
    topics: ["Risk Management", "Compliance", "FinTech"],
  }
]  

export const seminars: Seminar[] = [
  {
    id: "seminar1",
    title: "Cracking the Code Behind Big Data",
    description: "Explore how Big Data drives innovation in industries by uncovering patterns and insights. Learn about key tools like Hadoop, Spark, and cloud platforms that power this data revolution.",
    date: "May 5, 2025",
    time: "3:25 PM",
    duration: 50,
    topics: ["Big Data", "Hadoop", "Spark", "Cloud Platforms", "Data Analytics"],
    speakerId: "speaker1",
  },
  {
    id: "seminar2",
    title: "From Raw Data to Career-Ready Skills",
    description: "Gain hands-on experience with data collection, cleaning, and visualization using tools like Tableau and Power BI. Discover how to turn data skills into job opportunities in the Big Data industry.",
    date: "May 6, 2025",
    time: "9:20 AM",
    duration: 50,
    topics: ["Data Skills", "Data Cleaning", "Tableau", "Power BI", "Career Development"],
    speakerId: "speaker2",
  },
  {
    id: "seminar3",
    title: "Streamlining Project Management with GitHub: Collaboration, Version Control, and Workflow Optimization",
    description: "Unlock the full potential of GitHub for managing projects efficiently with branching, pull requests, and collaborative workflows. Understand how version control improves team productivity and code quality.",
    date: "May 6, 2025",
    time: "10:50 AM",
    duration: 50,
    topics: ["GitHub", "Project Management", "Collaboration", "Version Control", "Workflow"],
    speakerId: "speaker3",
  },
  {
    id: "seminar4",
    title: "From Pixels to Insights: Machine Learning for Image Processing and Analysis",
    description: "See how machine learning transforms raw images into valuable data through techniques like recognition and detection. Gain foundational knowledge of visual data analysis in real-world applications.",
    date: "May 6, 2025",
    time: "1:10 PM",
    duration: 50,
    topics: ["Machine Learning", "Image Processing", "Computer Vision", "Visual Data", "AI Applications"],
    speakerId: "speaker4",
  },
  {
    id: "seminar5",
    title: "The Power of Connection: Exploring the Salesforce World",
    description: "Get introduced to Salesforce and how it empowers businesses through customer relationship management and automation. Learn how Salesforce skills can boost your employability in today’s digital workplace.",
    date: "May 6, 2025",
    time: "2:25 PM",
    duration: 50,
    topics: ["Salesforce", "CRM", "Business Technology", "Digital Skills", "Customer Engagement"],
    speakerId: "speaker5",
  },
  {
    id: "seminar6",
    title: "The SAP Advantage: Streamlining Your Business Operations",
    description: "Unpack how SAP helps organizations manage finances, logistics, and operations through integrated systems. Understand the basics of ERP and why SAP is crucial in enterprise-level digital transformation.",
    date: "May 6, 2025",
    time: "3:40 PM",
    duration: 50,
    topics: ["SAP", "ERP", "Business Operations", "Enterprise Software", "Digital Transformation"],
    speakerId: "speaker6",
  },
  {
    id: "seminar7",
    title: "Demystifying Artificial Intelligence: Guide to Understanding and Navigating the Age of AI",
    description: "Learn the real-world applications and limitations of AI without the hype. This seminar provides a solid foundation for understanding how AI works and how it's shaping our future.",
    date: "May 8, 2025",
    time: "9:25 AM",
    duration: 50,
    topics: ["Artificial Intelligence", "AI Basics", "Technology Trends", "Future of Work", "Machine Learning"],
    speakerId: "speaker7",
  },
  {
    id: "seminar8",
    title: "AiLearn to AiEarn: Master Skills, Create Profits",
    description: "Discover how learning AI tools and technologies can open doors to freelancing, entrepreneurship, and high-demand tech roles. This session bridges AI education with real-world income-generating opportunities.",
    date: "May 8, 2025",
    time: "10:40 AM",
    duration: 50,
    topics: ["Artificial Intelligence", "Career Growth", "Tech Skills", "Entrepreneurship", "Freelancing"],
    speakerId: "speaker8",
  },
  {
    id: "seminar9",
    title: "Rise of the Machines: Exploring the World of Robotics",
    description: "Explore how robotics integrates sensors, AI, and automation to power machines that interact with the real world. Understand its growing role across industries and future possibilities.",
    date: "May 8, 2025",
    time: "1:40 PM",
    duration: 50,
    topics: ["Robotics", "Automation", "Sensors", "AI Integration", "Technology Innovation"],
    speakerId: "speaker9",
  },
  {
    id: "seminar10",
    title: "A Day in Fintech: Transforming Finance Through Innovation",
    description: "Dive into how technology is revolutionizing financial services, from digital payments to blockchain and AI. Understand the skills and trends shaping the future of fintech careers.",
    date: "May 8, 2025",
    time: "2:55 PM",
    duration: 50,
    topics: ["Fintech", "Financial Technology", "Blockchain", "Digital Banking", "AI in Finance"],
    speakerId: "speaker10",
  }
]

export const getSeminarsBySpeaker = (speakerId: string): Seminar[] => {
  return seminars.filter(seminar => seminar.speakerId === speakerId);
};

export const getSpeakerBySeminar = (seminarId: string): Speaker | undefined => {
  const seminar = seminars.find(s => s.id === seminarId);
  if (!seminar) return undefined;
  return speakers.find(speaker => speaker.id === seminar.speakerId);
};
